[Addon]
Enabled=True

[UI]
Font="Noto Sans CJK JP 11"
MenuFont="Noto Sans CJK JP 10"
TrayFont="Noto Sans CJK JP Bold 10"
TrayOutlineColor=#f5c2e7
TrayTextColor=#e0def4
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True
Theme=default
DarkTheme=default
UseDarkTheme=True
PerScreenDPI=True
ForceWaylandDPI=0
EnableFractionalScale=True
