# Quant BSPWM - MPV Input Bindings

# Navigation
l seek  5
h seek -5
L seek  30
H seek -30
j add volume -2
k add volume 2
m cycle mute

# Subtitles
v cycle sub-visibility
V cycle sub
J cycle sub down

# Audio track
a cycle audio

# Speed
[ multiply speed 0.9
] multiply speed 1.1
BS set speed 1.0

# Screenshot
s screenshot
S screenshot video

# Window
f cycle fullscreen
T cycle ontop
ESC set fullscreen no

# Playlist
> playlist-next
< playlist-prev

# Rotate
R cycle-values video-rotate 90 180 270 0

# Info
i script-binding stats/display-stats
I script-binding stats/display-stats-toggle
